name: CI tests

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  packages: write

jobs:
  #   build_docker:
  #     runs-on: ubuntu-latest

  #     steps:
  #       - name: Set lower case Github repository name
  #         run: |
  #           echo "GH_REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
  #         env:
  #           GITHUB_REPOSITORY: ${{ github.repository }}

  #       - name: Checkout code
  #         uses: actions/checkout@v3

  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v3

  #       - name: Login to Github Container Registry
  #         uses: docker/login-action@v3
  #         with:
  #           registry: ghcr.io
  #           username: ${{ github.actor }}
  #           password: ${{ secrets.GITHUB_TOKEN }}

  #       - name: Set proper tag name for Docker image
  #         run: |
  #           # Extracting the substring after "refs/heads/"
  #           BRANCH_NAME="${GITHUB_REF#refs/heads/}"

  #           # Covering to lower case and replacing "/" with "-"
  #           BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's|/|-|g')

  #           # Creating new environment variable
  #           echo "TAG_NAME=$BRANCH_NAME_LOWER" >> $GITHUB_ENV
  #         env:
  #           GITHUB_REF: ${{ github.ref_name }}

  #       - name: Build Docker image
  #         uses: docker/build-push-action@v3
  #         with:
  #           context: .
  #           file: ./Dockerfile
  #           push: true
  #           tags: ghcr.io/${{ env.GH_REPO_LC }}:${{ env.TAG_NAME }}

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run Vitest tests
        run: npm run test
        working-directory: ./app
  e2e:
    needs: tests

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Debugging
        run: cat package-lock.json
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
