name: CI tests

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  packages: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run Vitest tests
        run: npm run test
        working-directory: ./app

  e2e:
    needs: tests

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Navigate to app directory
        run: cd app
      - name: Install dependencies
        run: npm ci
        working-directory: ./app
      - name: Install Playwright
        run: npx playwright install
        working-directory: ./app
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./app

      - name: Run Vite server and Playwright tests
        run: npx start-server-and-test start http://localhost:3000 "npx playwright test"
        working-directory: ./app
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
